### ISSUE TITLE
茶姬签到在armbian盒子里运行报错

### ISSUE THREAD

**Issue by dz515704201** [Code-KKK/pycode#1]
Python版本: 3.11.8, 操作系统类型: Linux, 处理器架构: aarch64
当前环境符合运行要求
/ql/shell/otask.sh: line 95: 256808 Bus error               (core dumped) $timeoutCmd $which_program $file_param "${script_params[@]}"

**Comment by dz515704201** [comment]
只有1个账号，在X86里的青龙运行没问题

**Comment by Code-KKK** [comment]
看上去是青龙定时shell的报错，不像是脚本本身的问题。因为报错路径跟脚本没有相关联。
